# This theme is based on https://github.com/jekyll/minima
# Please refer above link to know the available configurations

title: "Backdoor-Resilient Federated Learning for NIDS"
remote_theme: cepdnaclk/eYY-project-theme
description: "Research project on backdoor-resilient federated learning for network intrusion detection systems"
markdown: kramdown

kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false
